### ISSUE TITLE
Configurable "UNLOCK" time

### ISSUE THREAD

**Issue by fkreiner** [sschaeffner/fabXaccess#48]
Make pulselength of UNLOCK mode configurable and include in device auto config

**Comment by sschaeffner** [comment]
This is a breaking change to the client API (currently v1). Therefore, it might be worth it to improve the whole client API or at least the auto-configuration part of it (e.g. JSON format such that future extensions like this are not breaking anymore).
It might also be interesting to combine this with  #47.

**Comment by sschaeffner** [comment]
It might also be worth thinking about bi-directional communication with clients, i.e. using websockets.
